### ISSUE TITLE
How to talk between ruby `Value` and C-API `**Ref`

### ISSUE THREAD

**Issue by saedrna** [SketchUp/sketchup-live-c-api#5]
Hi,

As said in the ReadMe `A third usage, officially supported since SketchUp 2019.2 it allows read only access to the open SketchUp model via Ruby C extensions.`, I think that it's possible to transform the ruby `Value` object to the C-API `Ref`  structures. For example, I can call something like rb_eval("SketchUp.active_model") to return a `Value` object and transform it into `SUModelRef`. Then do read only operations on it.

But how to do the transform? 

Currently I am using `rb_func_call` to directly operate on the ruby object, but it's too inconvinient.

Thanks,
Han

**Comment by thomthom** [comment]
>  For example, I can call something like rb_eval("SketchUp.active_model") to return a Value object and transform it into SUModelRef. Then do read only operations on it.

For the active model you should use `SUApplicationGetActiveModel`.

For other entities, such as faces, edges etc we don't have an API to exchange between Ruby `VALUE` and C API `SU*Ref` objects. But this is something that we have on our list.

Sidenote; I would recommend `rb_func_call` over `rb_eval`, parsing and evaluating a Ruby string will have extra overhead. I use a wrapper C++ function that simplifies it's usable.

**Comment by saedrna** [comment]
Good to hear this! In fact, I am also using rb_func_call.

Another question, is creation function using live api on your list, e.g. create a face and add to the model?

**Comment by thomthom** [comment]
At the moment, no. But I'd like to hear what you would want to use it for and why you want this over the existing Ruby API.

**Comment by saedrna** [comment]
If we only have read access, it's quite common that the whole plugin will look like this: starting a call from ruby -> wrapping a computation heavy function in c++ by accessing data using the c live api -> exposing interface to ruby (probably a general `Ruby::Array`) -> restructuring the data into `Sketchup::Face`

If we have write access, we can have a complete plugin with c/c++ only: call a functiom from a native MFC/QT UI -> get data using c live api -> processing -> write back to sketchup using c live api. This would be awesome, because we don't need to use `rb_func_call` `rb_eval_string`.

Although we can absolutely use ruby c api to do this (this is what I'm doing right now): call a function in native UI -> get data using `rb_func_call` -> transform the data to my own native c++ structure (such as face, vertex) (I have write a lot of wrappers) -> processing -> call `rb_func_call` to update the change back to SU. 

However, I am really tired of doing this, because `rb_func_call` is really not native in a c/c++ application.

**Comment by DanRathbun** [comment]
> For other entities, such as faces, edges etc we don't have an API to exchange between Ruby `VALUE` and C API `SU*Ref` objects. But this is something that we have on our list.

Note later in AUG 2020, the C API added conversion functions for the Live API usage.
This was for SketchUp **2020.2+** and API v**8.2** and higher.

See:

https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/ruby__api_8h.html

**Comment by saedrna** [comment]
> > For other entities, such as faces, edges etc we don't have an API to exchange between Ruby `VALUE` and C API `SU*Ref` objects. But this is something that we have on our list.
> 
> Note later in AUG 2020, the C API added conversion functions for the Live API usage. This was for SketchUp **2020.2+** and API v**8.2** and higher.
> 
> See:
> 
> https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/ruby__api_8h.html

Awesome! But I have finalized my SU project two years ago.

**Comment by DanRathbun** [comment]
The note was for anyone reading this thread.
